### ISSUE TITLE
Errors when trying to build

### ISSUE THREAD

**Issue by danrootdesign** [christophercliff/flatmarket#3]
When I try to run `flatmarket build ...` I get the following errors
```
/usr/local/lib/node_modules/flatmarket/lib/themes/default/index.jsx:27
            <div className="container">
            ^
SyntaxError: Unexpected token <
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .jsx] (/usr/local/lib/node_modules/flatmarket/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at getMarkup (/usr/local/lib/node_modules/flatmarket/lib/index.js:174:21)
    at buildLayout (/usr/local/lib/node_modules/flatmarket/lib/index.js:133:18)
    at tryCatcher (/usr/local/lib/node_modules/flatmarket/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/flatmarket/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/flatmarket/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/flatmarket/node_modules/bluebird/js/main/promise.js:244:10)
    at Async._drainQueue (/usr/local/lib/node_modules/flatmarket/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/flatmarket/node_modules/bluebird/js/main/async.js:133:10)
```

**Comment by christophercliff** [comment]
Looks like there's a problem with the Babel loader. Don't have a fix yet, but you should be able to run the same command with the `--dev` option.
