### ISSUE TITLE
Error trying to build app.js

### ISSUE THREAD

**Issue by johnsgill3** [christophercliff/flatmarket#44]
1. Cloned the repo
1. Changed to the `flatmarket-example` directory
1. Ran `npm install`
1. Tried to build the example and failed.

```
# ./node_modules/.bin/flatmarket src/flatmarket.json  --stripe-secret-key 12345 --component node_modules/flatmarket-theme-bananas/index.jsx 
(node:65846) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
ReferenceError: Unknown plugin "flatmarket/packages/flatmarket-example/node_modules/flatmarket-cli/node_modules/babel-plugin-transform-react-jsx" specified in "base" at 0, attempted to resolve relative to "flatmarket/packages/flatmarket-example/node_modules/flatmarket-theme-bananas"
    at flatmarket/packages/flatmarket-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (flatmarket/packages/flatmarket-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (flatmarket/packages/flatmarket-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (flatmarket/packages/flatmarket-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (flatmarket/packages/flatmarket-example/node_modules/babel-register/lib/node.js:103:45)
    at loader (flatmarket/packages/flatmarket-example/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .jsx] (flatmarket/packages/flatmarket-example/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getMarkup (flatmarket/packages/flatmarket-example/node_modules/flatmarket-cli/lib/index.js:171:21)
    at buildLayout (flatmarket/packages/flatmarket-example/node_modules/flatmarket-cli/lib/index.js:126:18)
    at tryCatcher (flatmarket/packages/flatmarket-example/node_modules/bluebird/js/main/util.js:26:23)
```

OSX
node -v = v7.7.1

Do I need to look at a different version of node? Am I doing something wrong?

**Comment by christophercliff** [comment]
Flatmarket requires [node v4](https://github.com/christophercliff/flatmarket/blob/master/package.json#L6). This is a limited by the [available AWS Lambda runtimes](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html) and also because I don't have time to keep up with latest node releases.

**Comment by johnsgill3** [comment]
Ah thank you. I knew it was something dumb I was doing. I have updated my nvm to use 4.x and seems that flatmarket is working much better now.
